import { describe, expect, it } from 'vitest';
import {
  buildSyntheticFounderProject,
  deterministicUuid,
  parseSeedEnvironment,
} from '../../scripts/seed-founder-example.js';

describe('synthetic founder example operator script', () => {
  it('builds deterministic, valid, clearly labeled approved demo data', () => {
    const first = buildSyntheticFounderProject('owner-a', '2026-07-15T00:00:00.000Z');
    const second = buildSyntheticFounderProject('owner-a', '2026-07-16T00:00:00.000Z');
    expect(first.id).toBe(second.id);
    expect(first.id).toMatch(/^[0-9a-f-]{36}$/);
    expect(first.title).toContain('[Synthetic]');
    expect(first.workflowStatus).toBe('approved');
    expect(first.briefVersions[0]?.sections.summary).toContain('not generated by GPT');
    expect(JSON.stringify(first)).not.toContain('access_token');
    expect(deterministicUuid('a')).not.toBe(deterministicUuid('b'));
  });

  it('requires an explicit target and production confirmation', () => {
    expect(parseSeedEnvironment(['--environment=staging'])).toBe('staging');
    expect(parseSeedEnvironment(['--environment=production', '--confirm-production'])).toBe(
      'production',
    );
    expect(() => parseSeedEnvironment([])).toThrow('SEED_ENVIRONMENT_REQUIRED');
    expect(() => parseSeedEnvironment(['--environment=production'])).toThrow(
      'PRODUCTION_CONFIRMATION_REQUIRED',
    );
  });
});
